CREATE OR REPLACE FUNCTION OTIMIZA.SH_QTDE_TEC_MASC (
    TP_TEC    VARCHAR2,
    V_MASC_ID NUMBER
) RETURN NUMBER
IS
    V_QTDE_TEC NUMBER;
BEGIN
	IF TP_TEC = 'CAIXA' THEN
		SELECT
		MAX(Z.QTDE)
		INTO V_QTDE_TEC 
		FROM (
				SELECT
				MAX(X.DIVISOR) DIVISOR,
				X.QTDE
				FROM (	
						SELECT
						TCONFIG_ITENS.TMASC_ITEM_ID ID_MASC,
						COUNT(SH_QTDE_TEC.ID_REGRA) CONTADOR,
						COUNT(SH_QTDE_TEC.ID_REGRA)/(SELECT DISTINCT COUNT(SH_QTDE_TEC2.SEQ) FROM SH_QTDE_TEC SH_QTDE_TEC2 WHERE SH_QTDE_TEC2.ID_REGRA = SH_QTDE_TEC.ID_REGRA) DIVISOR,
						MAX(SH_QTDE_TEC.QTDE) QTDE
						FROM focco3i.TCONFIG_ITENS
						JOIN focco3i.TITENS_EMPR ON TITENS_EMPR.ID = TCONFIG_ITENS.ITEMPR_ID
						JOIN focco3i.TITENS ON TITENS.ID = TITENS_EMPR.ITEM_ID
						JOIN otimiza.SH_QTDE_TEC ON TITENS_EMPR.ID = SH_QTDE_TEC.ID_ITEMPR AND TCONFIG_ITENS.TCARAC_ID = SH_QTDE_TEC.ID_CARAC AND TCONFIG_ITENS.TVAR_ID = SH_QTDE_TEC.ID_VAR AND TCONFIG_ITENS.SEQ = SH_QTDE_TEC.SEQ
						JOIN otimiza.SH_CONFIGURADOR ON SH_CONFIGURADOR.ID = SH_QTDE_TEC.ID_REGRA
						WHERE TCONFIG_ITENS.TMASC_ITEM_ID = V_MASC_ID
						AND (SH_CONFIGURADOR.ITEM_FILHO LIKE '%CAIXA')
						GROUP BY TCONFIG_ITENS.TMASC_ITEM_ID, SH_QTDE_TEC.ID_REGRA, SH_QTDE_TEC.QTDE
					) X
				WHERE X.CONTADOR = (	
										SELECT MAX(Y.CONTADOR)
										FROM (	
												SELECT
												TCONFIG_ITENS.TMASC_ITEM_ID ID_MASC,
												COUNT(SH_QTDE_TEC.ID_REGRA) CONTADOR
												FROM focco3i.TCONFIG_ITENS
												JOIN focco3i.TITENS_EMPR ON TITENS_EMPR.ID = TCONFIG_ITENS.ITEMPR_ID
												JOIN focco3i.TITENS ON TITENS.ID = TITENS_EMPR.ITEM_ID
												JOIN otimiza.SH_QTDE_TEC ON TITENS_EMPR.ID = SH_QTDE_TEC.ID_ITEMPR AND TCONFIG_ITENS.TCARAC_ID = SH_QTDE_TEC.ID_CARAC AND TCONFIG_ITENS.TVAR_ID = SH_QTDE_TEC.ID_VAR AND TCONFIG_ITENS.SEQ = SH_QTDE_TEC.SEQ
												JOIN otimiza.SH_CONFIGURADOR ON SH_CONFIGURADOR.ID = SH_QTDE_TEC.ID_REGRA
												WHERE TCONFIG_ITENS.TMASC_ITEM_ID = V_MASC_ID
												AND (SH_CONFIGURADOR.ITEM_FILHO LIKE '%CAIXA')
												GROUP BY TCONFIG_ITENS.TMASC_ITEM_ID, SH_QTDE_TEC.ID_REGRA
											 ) Y
										WHERE Y.ID_MASC = X.ID_MASC
									)
				GROUP BY X.QTDE
			) Z
		;
	ELSIF TP_TEC = 'MODELO' THEN
		SELECT
		MAX(Z.QTDE)
		INTO V_QTDE_TEC 
		FROM(
				SELECT
				MAX(X.DIVISOR) DIVISOR,
				X.QTDE
				FROM (	
						SELECT
						TCONFIG_ITENS.TMASC_ITEM_ID ID_MASC,
						COUNT(SH_QTDE_TEC.ID_REGRA) CONTADOR,
						COUNT(SH_QTDE_TEC.ID_REGRA)/(SELECT DISTINCT COUNT(SH_QTDE_TEC2.SEQ) FROM SH_QTDE_TEC SH_QTDE_TEC2 WHERE SH_QTDE_TEC2.ID_REGRA = SH_QTDE_TEC.ID_REGRA) DIVISOR,
						MAX(SH_QTDE_TEC.QTDE) QTDE
						FROM focco3i.TCONFIG_ITENS
						JOIN focco3i.TITENS_EMPR ON TITENS_EMPR.ID = TCONFIG_ITENS.ITEMPR_ID
						JOIN focco3i.TITENS ON TITENS.ID = TITENS_EMPR.ITEM_ID
						JOIN otimiza.SH_QTDE_TEC ON TITENS_EMPR.ID = SH_QTDE_TEC.ID_ITEMPR AND TCONFIG_ITENS.TCARAC_ID = SH_QTDE_TEC.ID_CARAC AND TCONFIG_ITENS.TVAR_ID = SH_QTDE_TEC.ID_VAR AND TCONFIG_ITENS.SEQ = SH_QTDE_TEC.SEQ
						JOIN otimiza.SH_CONFIGURADOR ON SH_CONFIGURADOR.ID = SH_QTDE_TEC.ID_REGRA
						WHERE TCONFIG_ITENS.TMASC_ITEM_ID = V_MASC_ID
						AND (SH_CONFIGURADOR.ITEM_FILHO NOT LIKE '%CAIXA')
						GROUP BY TCONFIG_ITENS.TMASC_ITEM_ID, SH_QTDE_TEC.ID_REGRA, SH_QTDE_TEC.QTDE
					) X
				WHERE X.CONTADOR = (	
										SELECT MAX(Y.CONTADOR)
										FROM (	
												SELECT
												TCONFIG_ITENS.TMASC_ITEM_ID ID_MASC,
												COUNT(SH_QTDE_TEC.ID_REGRA) CONTADOR
												FROM focco3i.TCONFIG_ITENS
												JOIN focco3i.TITENS_EMPR ON TITENS_EMPR.ID = TCONFIG_ITENS.ITEMPR_ID
												JOIN focco3i.TITENS ON TITENS.ID = TITENS_EMPR.ITEM_ID
												JOIN otimiza.SH_QTDE_TEC ON TITENS_EMPR.ID = SH_QTDE_TEC.ID_ITEMPR AND TCONFIG_ITENS.TCARAC_ID = SH_QTDE_TEC.ID_CARAC AND TCONFIG_ITENS.TVAR_ID = SH_QTDE_TEC.ID_VAR AND TCONFIG_ITENS.SEQ = SH_QTDE_TEC.SEQ
												JOIN otimiza.SH_CONFIGURADOR ON SH_CONFIGURADOR.ID = SH_QTDE_TEC.ID_REGRA
												WHERE TCONFIG_ITENS.TMASC_ITEM_ID = V_MASC_ID
												AND (SH_CONFIGURADOR.ITEM_FILHO NOT LIKE '%CAIXA')
												GROUP BY TCONFIG_ITENS.TMASC_ITEM_ID, SH_QTDE_TEC.ID_REGRA
											 ) Y
										WHERE Y.ID_MASC = X.ID_MASC
									)
				GROUP BY X.QTDE
			) Z
		;
	END IF;
    RETURN V_QTDE_TEC;
END;
