CREATE OR REPLACE FUNCTION OTIMIZA.SH_QTDE_TEC_PRVD (TP_TEC VARCHAR2, V_REGRA_ID NUMBER)
RETURN NUMBER
IS
V_QTDE_TEC NUMBER;
BEGIN
	IF TP_TEC = 'CAIXA' THEN 
		SELECT
		MAX(Z.QTDE)
		INTO V_QTDE_TEC
		FROM(
				SELECT 
				MAX(X.DIVISOR) DIVISOR,
				X.QTDE
				FROM (	
						SELECT
						TPRECOSVEN_IT.ID ID_REGRA_PRECO,
						COUNT(SH_QTDE_TEC.ID_REGRA) CONTADOR,
						COUNT(SH_QTDE_TEC.ID_REGRA)/(SELECT COUNT(DISTINCT SH_QTDE_TEC2.SEQ) FROM SH_QTDE_TEC SH_QTDE_TEC2 WHERE SH_QTDE_TEC2.ID_REGRA = SH_QTDE_TEC.ID_REGRA) DIVISOR,
						MAX(SH_QTDE_TEC.QTDE) QTDE
						FROM focco3i.TPRECOSVEN_IT
						JOIN focco3i.TITENS_COMERCIAL ON TITENS_COMERCIAL.ID = TPRECOSVEN_IT.ITCM_ID
						JOIN focco3i.TPRC_REGRAS_COM ON TPRC_REGRAS_COM.TPRVEN_IT_ID = TPRECOSVEN_IT.ID
						JOIN focco3i.TPRC_REGRAS_VAR_COM ON TPRC_REGRAS_VAR_COM.REGRA_COM_ID = TPRC_REGRAS_COM.ID
						JOIN otimiza.SH_QTDE_TEC ON TITENS_COMERCIAL.ITEMPR_ID = SH_QTDE_TEC.ID_ITEMPR 
												AND TPRC_REGRAS_COM.TCARAC_ID = SH_QTDE_TEC.ID_CARAC 
												AND TPRC_REGRAS_VAR_COM.TVAR_ID = SH_QTDE_TEC.ID_VAR
						JOIN otimiza.SH_CONFIGURADOR ON SH_CONFIGURADOR.ID = SH_QTDE_TEC.ID_REGRA
						WHERE TPRECOSVEN_IT.ID = V_REGRA_ID
						AND (SH_CONFIGURADOR.ITEM_FILHO LIKE '%CAIXA')
						GROUP BY TPRECOSVEN_IT.ID, SH_QTDE_TEC.ID_REGRA
					) X
				
				WHERE X.CONTADOR = (
										SELECT MAX(Y.CONTADOR)
										FROM (	SELECT
												TPRECOSVEN_IT.ID ID_REGRA_PRECO,
												SH_QTDE_TEC.ID_REGRA ID_REGRA_CONF,
												COUNT(SH_QTDE_TEC.ID_REGRA) CONTADOR
												FROM focco3i.TPRECOSVEN_IT
												JOIN focco3i.TITENS_COMERCIAL ON TITENS_COMERCIAL.ID = TPRECOSVEN_IT.ITCM_ID
												JOIN focco3i.TPRC_REGRAS_COM ON TPRC_REGRAS_COM.TPRVEN_IT_ID = TPRECOSVEN_IT.ID
												JOIN focco3i.TPRC_REGRAS_VAR_COM ON TPRC_REGRAS_VAR_COM.REGRA_COM_ID = TPRC_REGRAS_COM.ID
												JOIN otimiza.SH_QTDE_TEC ON TITENS_COMERCIAL.ITEMPR_ID = SH_QTDE_TEC.ID_ITEMPR 
																		AND TPRC_REGRAS_COM.TCARAC_ID = SH_QTDE_TEC.ID_CARAC 
																		AND TPRC_REGRAS_VAR_COM.TVAR_ID = SH_QTDE_TEC.ID_VAR
												JOIN otimiza.SH_CONFIGURADOR ON SH_CONFIGURADOR.ID = SH_QTDE_TEC.ID_REGRA
												WHERE TPRECOSVEN_IT.ID = V_REGRA_ID
												AND (SH_CONFIGURADOR.ITEM_FILHO LIKE '%CAIXA')
												GROUP BY TPRECOSVEN_IT.ID, SH_QTDE_TEC.ID_REGRA
											) Y
									)
				GROUP BY X.QTDE
			) Z
		;
	ELSIF TP_TEC = 'MODELO' THEN
		SELECT
		MAX(Z.QTDE)
		INTO V_QTDE_TEC
		FROM(
				SELECT 
				MAX(X.DIVISOR) DIVISOR,
				X.QTDE
				FROM (	
						SELECT
						TPRECOSVEN_IT.ID ID_REGRA_PRECO,
						COUNT(SH_QTDE_TEC.ID_REGRA) CONTADOR,
						COUNT(SH_QTDE_TEC.ID_REGRA)/(SELECT COUNT(DISTINCT SH_QTDE_TEC2.SEQ) FROM SH_QTDE_TEC SH_QTDE_TEC2 WHERE SH_QTDE_TEC2.ID_REGRA = SH_QTDE_TEC.ID_REGRA) DIVISOR,
						MAX(SH_QTDE_TEC.QTDE) QTDE
						FROM focco3i.TPRECOSVEN_IT
						JOIN focco3i.TITENS_COMERCIAL ON TITENS_COMERCIAL.ID = TPRECOSVEN_IT.ITCM_ID
						JOIN focco3i.TPRC_REGRAS_COM ON TPRC_REGRAS_COM.TPRVEN_IT_ID = TPRECOSVEN_IT.ID
						JOIN focco3i.TPRC_REGRAS_VAR_COM ON TPRC_REGRAS_VAR_COM.REGRA_COM_ID = TPRC_REGRAS_COM.ID
						JOIN otimiza.SH_QTDE_TEC ON TITENS_COMERCIAL.ITEMPR_ID = SH_QTDE_TEC.ID_ITEMPR 
												AND TPRC_REGRAS_COM.TCARAC_ID = SH_QTDE_TEC.ID_CARAC 
												AND TPRC_REGRAS_VAR_COM.TVAR_ID = SH_QTDE_TEC.ID_VAR
						JOIN otimiza.SH_CONFIGURADOR ON SH_CONFIGURADOR.ID = SH_QTDE_TEC.ID_REGRA
						WHERE TPRECOSVEN_IT.ID = V_REGRA_ID
						AND (SH_CONFIGURADOR.ITEM_FILHO NOT LIKE '%CAIXA')
						GROUP BY TPRECOSVEN_IT.ID, SH_QTDE_TEC.ID_REGRA
					) X
				
				WHERE X.CONTADOR = (
										SELECT MAX(Y.CONTADOR)
										FROM (	SELECT
												TPRECOSVEN_IT.ID ID_REGRA_PRECO,
												SH_QTDE_TEC.ID_REGRA ID_REGRA_CONF,
												COUNT(SH_QTDE_TEC.ID_REGRA) CONTADOR
												FROM focco3i.TPRECOSVEN_IT
												JOIN focco3i.TITENS_COMERCIAL ON TITENS_COMERCIAL.ID = TPRECOSVEN_IT.ITCM_ID
												JOIN focco3i.TPRC_REGRAS_COM ON TPRC_REGRAS_COM.TPRVEN_IT_ID = TPRECOSVEN_IT.ID
												JOIN focco3i.TPRC_REGRAS_VAR_COM ON TPRC_REGRAS_VAR_COM.REGRA_COM_ID = TPRC_REGRAS_COM.ID
												JOIN otimiza.SH_QTDE_TEC ON TITENS_COMERCIAL.ITEMPR_ID = SH_QTDE_TEC.ID_ITEMPR 
																		AND TPRC_REGRAS_COM.TCARAC_ID = SH_QTDE_TEC.ID_CARAC 
																		AND TPRC_REGRAS_VAR_COM.TVAR_ID = SH_QTDE_TEC.ID_VAR
												JOIN otimiza.SH_CONFIGURADOR ON SH_CONFIGURADOR.ID = SH_QTDE_TEC.ID_REGRA
												WHERE TPRECOSVEN_IT.ID = V_REGRA_ID
												AND (SH_CONFIGURADOR.ITEM_FILHO NOT LIKE '%CAIXA')
												GROUP BY TPRECOSVEN_IT.ID, SH_QTDE_TEC.ID_REGRA
											) Y
									)
				GROUP BY X.QTDE
			) Z
		;
	END IF;
	RETURN V_QTDE_TEC;
END;
