CREATE OR REPLACE FUNCTION OTIMIZA.SH_PRECO_SERV_TERC_FC (V_REGRA NUMBER)
RETURN NUMBER
IS
V_PRECO NUMBER;
BEGIN
	SELECT K.ID_PRECO INTO V_PRECO
	FROM(	SELECT 
			X.ID_PRECO,
			X.ID_REGRA,
			CASE WHEN X.ID_MASC IS NOT NULL THEN 1 ELSE CASE WHEN X.CONT_1 = X.CONT_2 THEN CASE WHEN (X.CONT_1/X.CONT_3) = 1 THEN 1 ELSE NULL END END END RESULTADO
			FROM (	SELECT
					TOPER_PRECOS_TERC.ID ID_PRECO,
					SH_PRECO_SERV_TERC_REGRA.ID_REGRA,
					SH_PRECO_SERV_TERC.ID_MASC,
					
					(SELECT COUNT(SH_PRECO_SERV_TERC_REGRA2.ID) 
					FROM SH_PRECO_SERV_TERC_REGRA SH_PRECO_SERV_TERC_REGRA2 
					WHERE SH_PRECO_SERV_TERC_REGRA2.ID_REGRA = SH_PRECO_SERV_TERC_REGRA.ID_REGRA) CONT_1,
					
					(SELECT COUNT(TTERC_REGRAS_VAR2.ID) 
					FROM focco3i.TTERC_REGRAS_VAR TTERC_REGRAS_VAR2 
					JOIN focco3i.TTERC_REGRAS TTERC_REGRAS2 ON TTERC_REGRAS2.ID = TTERC_REGRAS_VAR2.TERC_REGRA_ID 
					WHERE TTERC_REGRAS2.OPER_PRC_T_ID = TOPER_PRECOS_TERC.ID) CONT_2,
					
					COUNT(TTERC_REGRAS_VAR.ID) CONT_3
					
					FROM focco3i.TOPER_PRECOS_TERC
					
					LEFT JOIN focco3i.TTERC_REGRAS ON TTERC_REGRAS.OPER_PRC_T_ID = TOPER_PRECOS_TERC.ID
					LEFT JOIN focco3i.TTERC_REGRAS_VAR ON TTERC_REGRAS_VAR.TERC_REGRA_ID = TTERC_REGRAS.ID
					LEFT JOIN otimiza.SH_PRECO_SERV_TERC ON SH_PRECO_SERV_TERC.ID_MASC = TOPER_PRECOS_TERC.TMASC_ITEM_ID
														AND SH_PRECO_SERV_TERC.ID_ITEM = TOPER_PRECOS_TERC.ITEMPR_ID
								  						AND SH_PRECO_SERV_TERC.ID_FORN = TOPER_PRECOS_TERC.EMPFOR_ID
					LEFT JOIN otimiza.SH_PRECO_SERV_TERC_REGRA ON SH_PRECO_SERV_TERC_REGRA.ID_CARAC = TTERC_REGRAS.TCARAC_ID
																AND SH_PRECO_SERV_TERC_REGRA.ID_VAR = TTERC_REGRAS_VAR.TVAR_ID
																AND SH_PRECO_SERV_TERC_REGRA.ID_ITEM = TOPER_PRECOS_TERC.ITEMPR_ID
													  			AND SH_PRECO_SERV_TERC_REGRA.ID_FORN = TOPER_PRECOS_TERC.EMPFOR_ID
												  
					WHERE (SH_PRECO_SERV_TERC_REGRA.ID_REGRA = V_REGRA OR SH_PRECO_SERV_TERC.ID = V_REGRA)
					GROUP BY TOPER_PRECOS_TERC.ID, SH_PRECO_SERV_TERC_REGRA.ID_REGRA, SH_PRECO_SERV_TERC.ID_MASC
				) X
			ORDER BY X.ID_REGRA
		) K
	WHERE K.RESULTADO = 1;
	RETURN V_PRECO;
END;
