CREATE OR REPLACE FUNCTION OTIMIZA.SH_CONTADOR (V_STRING VARCHAR2, V_SUBSTRING VARCHAR2)
RETURN INTEGER
IS
V_POSITION INTEGER := LENGTH(V_STRING);
V_COUNT INTEGER := 0;
BEGIN
	WHILE V_POSITION > 0 LOOP
		IF INSTR(V_STRING,V_SUBSTRING,1,V_POSITION) > 0 
			THEN V_COUNT := V_COUNT + 1;	
		END IF;
		V_POSITION := V_POSITION - 1;
	END LOOP;
	RETURN V_COUNT;
END;
