CREATE OR REPLACE TRIGGER FOCCO3I.SH_TEC_FORN_ITEM_TERC
BEFORE INSERT ON TITENS_AVISO_RECEB
REFERENCING 
 NEW AS NEW
 OLD AS OLD
FOR EACH ROW
DECLARE
	V_PDV_NUM		INTEGER;
	V_FOR_ID_AVR 	INTEGER;
	V_CLI_ID 		INTEGER;
	V_EST_ID 		INTEGER;
BEGIN
	IF :new.ITES_ID = 101465 THEN
		SELECT TPEDIDOS_VENDA.NUM_PEDIDO INTO V_PDV_NUM FROM TCONFIG_ITENS LEFT JOIN TPEDIDOS_VENDA ON TPEDIDOS_VENDA.NUM_PEDIDO = TCONFIG_ITENS.VALOR AND TPEDIDOS_VENDA.TIPO = 'PDV' WHERE TCONFIG_ITENS.TCARAC_ID = 4890 AND TCONFIG_ITENS.TMASC_ITEM_ID = :new.TMASC_ITEM_ID;
		IF V_PDV_NUM IS NOT NULL THEN
			SELECT CLI_ID INTO V_CLI_ID FROM TPEDIDOS_VENDA WHERE TPEDIDOS_VENDA.EMPR_ID = 1 AND TPEDIDOS_VENDA.TIPO = 'PDV' AND TPEDIDOS_VENDA.NUM_PEDIDO = V_PDV_NUM;
			SELECT EST_ID_FAT INTO V_EST_ID FROM TPEDIDOS_VENDA WHERE TPEDIDOS_VENDA.EMPR_ID = 1 AND TPEDIDOS_VENDA.TIPO = 'PDV' AND TPEDIDOS_VENDA.NUM_PEDIDO = V_PDV_NUM;
			SELECT FORN_ID INTO V_FOR_ID_AVR FROM TAVISOS_RECEB WHERE ID = :new.AVR_ID;
			UPDATE TITENS_ENG_CONF SET CLI_ID = V_CLI_ID, EST_ID = V_EST_ID, FORN_ID = V_FOR_ID_AVR WHERE TMASC_ITEM_ID = :new.TMASC_ITEM_ID;  
		END IF;
	END IF;
END;