CREATE OR REPLACE TRIGGER FOCCO3I.SH_TEC_FORN_NCM
BEFORE  INSERT ON TITENS_CTAB_CONF
REFERENCING 
 NEW AS NEW
 OLD AS OLD
FOR EACH ROW
DECLARE
	V_CLAS_FISC_ID		INTEGER;
BEGIN
	IF :new.ITCN_ID = 104718 THEN
		SELECT TCLAS_FISC.ID INTO V_CLAS_FISC_ID FROM TCONFIG_ITENS LEFT JOIN TCLAS_FISC ON TCLAS_FISC.CLAS_FISC = TCONFIG_ITENS.TEXTO	WHERE TCONFIG_ITENS.TMASC_ITEM_ID = :new.TMASC_ITEM_ID AND TCONFIG_ITENS.TCARAC_ID = 3487;
		IF V_CLAS_FISC_ID IS NOT NULL THEN
			:new.clas_fisc_id := V_CLAS_FISC_ID;  
			:new.clas_fisc_compra_id := V_CLAS_FISC_ID;
		END IF;
	END IF;
END;