CREATE OR REPLACE TRIGGER FOCCO3I.SH_DT_RECEB_AVR
BEFORE  INSERT ON TNFS_ENTRADA
REFERENCING 
 NEW AS NEW
 OLD AS OLD
FOR EACH ROW
DECLARE
	V_ID_AVR	INTEGER;
	V_DT_RECEB	DATE;
BEGIN
	IF :NEW.TIPO_NOTA = 'A' THEN
		SELECT TAVISOS_RECEB.ID INTO V_ID_AVR FROM TAVISOS_RECEB WHERE TAVISOS_RECEB.NUM_NF = :NEW.NUM_NF AND TAVISOS_RECEB.SERIE = :NEW.SERIE AND TAVISOS_RECEB.FORN_ID = :NEW.TFOR_ID;
		SELECT TAVISOS_RECEB.DT_ENT INTO V_DT_RECEB FROM TAVISOS_RECEB WHERE TAVISOS_RECEB.NUM_NF = :NEW.NUM_NF AND TAVISOS_RECEB.SERIE = :NEW.SERIE AND TAVISOS_RECEB.FORN_ID = :NEW.TFOR_ID;
		IF TO_CHAR(V_DT_RECEB,'MM/YYYY') <> TO_CHAR(:NEW.DT_ENT,'MM/YYYY') THEN
			UPDATE TAVISOS_RECEB SET TAVISOS_RECEB.DT_ENT = ADD_MONTHS(TAVISOS_RECEB.DT_ENT, -12) WHERE TAVISOS_RECEB.ID = V_ID_AVR;
		END IF;
	END IF;
END;