CREATE OR REPLACE FORCE EDITIONABLE VIEW "FOCCO3I"."SH_PROC_EXP_DESP" ("ID_PROC_EXT", "FORNECEDOR", "TIPO", "NUMERO", "EMISSAO", "SEQ", "ITEM", "VALOR") AS 
  SELECT
TPROCESSOS_EXTERIOR.ID "ID_PROC_EXT",
TFORNECEDORES.DESCRICAO "FORNECEDOR",
'PDC' "TIPO",
TPED_COMPRA.cod_pedc || '' "NUMERO",
TO_CHAR(TPED_COMPRA.DT_EMIS,'DD/MM/YYYY') "EMISSAO",
TPEDC_ITEM.SEQ_IT "SEQ",
TPEDC_ITEM.DESCRICAO_ITEM "ITEM",
ROUND(TPED_COMPRA_PROC_EXT.VALOR/TPED_COMPRA.TOT_LIQUIDO*TPEDC_ITEM.TOT_LIQUIDO,2) "VALOR"
FROM focco3i.TPROCESSOS_EXTERIOR

JOIN TPED_COMPRA_PROC_EXT ON TPED_COMPRA_PROC_EXT.PROC_EXT_ID = TPROCESSOS_EXTERIOR.ID
JOIN TPED_COMPRA ON TPED_COMPRA.ID = TPED_COMPRA_PROC_EXT.PEDC_ID
JOIN TPEDC_ITEM ON TPEDC_ITEM.TPEDC_ID = TPED_COMPRA.ID
JOIN TFORNECEDORES ON TFORNECEDORES.ID = TPED_COMPRA.TFOR_ID

UNION ALL

SELECT
TPROCESSOS_EXTERIOR.ID "ID_PROC_EXT",
TFORNECEDORES.DESCRICAO "FORNECEDOR",
'NFE' "TIPO",
TNFS_ENTRADA.NUM_NF || '-' || TNFS_ENTRADA.SERIE "NUMERO",
TO_CHAR(TNFS_ENTRADA.DT_EMIS,'DD/MM/YYYY') "EMISSAO",
TITENS_NFE.NUM_ITE "SEQ",
TITENS_NFE.DESCRICAO  "ITEM",
ROUND(TNFS_ENTRADA_PROC_EXT.VALOR/TNFS_ENTRADA.VLR_TOTAL*TITENS_NFE.VLR_TOTAL,2) "VALOR"
FROM focco3i.TPROCESSOS_EXTERIOR

JOIN TNFS_ENTRADA_PROC_EXT ON TNFS_ENTRADA_PROC_EXT.PROC_EXT_ID = TPROCESSOS_EXTERIOR.ID
JOIN TNFS_ENTRADA ON TNFS_ENTRADA.ID = TNFS_ENTRADA_PROC_EXT.NFE_ID
JOIN TITENS_NFE ON TITENS_NFE.NFE_ID = TNFS_ENTRADA.ID
JOIN TFORNECEDORES ON TFORNECEDORES.ID = TNFS_ENTRADA.TFOR_ID;
