CREATE OR REPLACE FORCE EDITIONABLE VIEW "FOCCO3I"."SH_AUDIT_INSERT" ("TABELA", "ID", "DTA_OPERACAO_LOG", "DES_USUARIO_BANCO_LOG", "DES_USUARIO_FOCCO3I_LOG", "REFERENCIA") AS 
  SELECT
'TPORTADORES' "TABELA",
TPORTADORES.ID,
DTA_OPERACAO_LOG,
DES_USUARIO_BANCO_LOG,
DES_USUARIO_FOCCO3I_LOG,
TPORTADORES.COD_POR || ' - ' || TPORTADORES.DESCRICAO "REFERENCIA"
FROM TPORTADORES
JOIN F3I_LOG_TPORTADORES ON F3I_LOG_TPORTADORES.ID = TPORTADORES.ID AND COD_OPERACAO_LOG = 'I'

UNION ALL

SELECT
'TTP_CCR' "TABELA",
TTP_CCR.ID,
DTA_OPERACAO_LOG,
DES_USUARIO_BANCO_LOG,
DES_USUARIO_FOCCO3I_LOG,
TTP_CCR.COD_TP_CCR || ' - ' || TTP_CCR.DESCRICAO "REFERENCIA"
FROM TTP_CCR
JOIN F3I_LOG_TTP_CCR ON F3I_LOG_TTP_CCR.ID = TTP_CCR.ID AND COD_OPERACAO_LOG = 'I'

UNION ALL

SELECT
'TTP_CP' "TABELA",
TTP_CP.ID,
DTA_OPERACAO_LOG,
DES_USUARIO_BANCO_LOG,
DES_USUARIO_FOCCO3I_LOG,
TTP_CP.COD_TP_CP || ' - ' || TTP_CP.DESCRICAO "REFERENCIA"
FROM TTP_CP
JOIN F3I_LOG_TTP_CP ON F3I_LOG_TTP_CP.ID = TTP_CP.ID AND COD_OPERACAO_LOG = 'I'

UNION ALL

SELECT
'TTP_CR' "TABELA",
TTP_CR.ID,
DTA_OPERACAO_LOG,
DES_USUARIO_BANCO_LOG,
DES_USUARIO_FOCCO3I_LOG,
TTP_CR.COD_TP_CR || ' - ' || TTP_CR.DESCRICAO "REFERENCIA"
FROM TTP_CR
JOIN F3I_LOG_TTP_CR ON F3I_LOG_TTP_CR.ID = TTP_CR.ID AND COD_OPERACAO_LOG = 'I'

UNION ALL

SELECT
'TTP_DOC' "TABELA",
TTP_DOC.ID,
DTA_OPERACAO_LOG,
DES_USUARIO_BANCO_LOG,
DES_USUARIO_FOCCO3I_LOG,
TTP_DOC.COD_TP_DOC || ' - ' || TTP_DOC.DESCRICAO "REFERENCIA"
FROM TTP_DOC
JOIN F3I_LOG_TTP_DOC ON F3I_LOG_TTP_DOC.ID = TTP_DOC.ID AND COD_OPERACAO_LOG = 'I';
